import { randomUUID } from "node:crypto";
import path from "node:path";

import { ensureDir, readJson, updateJson, writeJson, writeText } from "./fs.js";
import type { MemoryItem, MemorySweepReport, RetrievalHit } from "./types.js";

function lexicalScore(query: string, content: string): number {
  const queryTokens = new Set(query.toLowerCase().split(/\W+/).filter(Boolean));
  const contentTokens = content.toLowerCase().split(/\W+/).filter(Boolean);
  let matches = 0;
  for (const token of contentTokens) {
    if (queryTokens.has(token)) {
      matches += 1;
    }
  }
  return matches / Math.max(queryTokens.size, 1);
}

export class JsonMemoryStore {
  constructor(private readonly stateRoot: string) {}

  private get filePath(): string {
    return path.join(this.stateRoot, "memory.json");
  }

  async add(item: Omit<MemoryItem, "createdAt" | "id">): Promise<MemoryItem> {
    const record: MemoryItem = {
      ...item,
      createdAt: new Date().toISOString(),
      id: randomUUID(),
    };
    await updateJson<MemoryItem[]>(this.filePath, [], (current) => [
      ...current,
      record,
    ]);
    return record;
  }

  async list(namespace: string): Promise<MemoryItem[]> {
    const all = await readJson<MemoryItem[]>(this.filePath, []);
    return all.filter((item) => item.namespace === namespace);
  }

  async replaceNamespace(
    namespace: string,
    items: MemoryItem[],
  ): Promise<void> {
    await updateJson<MemoryItem[]>(this.filePath, [], (all) => [
      ...all.filter((item) => item.namespace !== namespace),
      ...items,
    ]);
  }

  async search(namespace: string, query: string): Promise<MemoryItem[]> {
    const all = await this.list(namespace);
    return all
      .map((item) => ({
        item,
        score: lexicalScore(query, item.content),
      }))
      .filter((entry) => entry.score > 0)
      .sort((left, right) => right.score - left.score)
      .map((entry) => entry.item);
  }
}

function normalizeMemoryContent(content: string): string {
  return content.toLowerCase().replace(/\s+/g, " ").trim();
}

function memoryRecencyScore(item: MemoryItem, now: Date): number {
  const ageDays = Math.max(
    0,
    (now.getTime() - new Date(item.createdAt).getTime()) / 86_400_000,
  );
  return Math.max(0, 1 - ageDays / 90);
}

function shouldExpireMemory(item: MemoryItem, now: Date): boolean {
  if (!item.freshnessTtlSeconds) {
    return false;
  }
  return (
    now.getTime() - new Date(item.createdAt).getTime() >
    item.freshnessTtlSeconds * 1_000
  );
}

function renderMemoryVault(namespace: string, items: MemoryItem[]): string {
  const sections = items
    .map((item) =>
      [
        `## ${item.kind}: ${item.id}`,
        "",
        `confidence: ${item.confidence.toFixed(2)}`,
        `createdAt: ${item.createdAt}`,
        `provenance: ${item.provenance.join(", ") || "unknown"}`,
        "",
        item.content.trim(),
      ].join("\n"),
    )
    .join("\n\n");
  return [
    `# Latte Memory Vault: ${namespace}`,
    "",
    "This file is generated by `latte memory sweep`. Edit source memories through the CLI or JSON store.",
    "",
    sections,
    "",
  ].join("\n");
}

export async function sweepMemory(
  stateRoot: string,
  namespace: string,
  options: { maxPromoted?: number; minScore?: number; now?: Date } = {},
): Promise<MemorySweepReport> {
  const now = options.now ?? new Date();
  const store = new JsonMemoryStore(stateRoot);
  const input = await store.list(namespace);
  const seen = new Set<string>();
  const retained: MemoryItem[] = [];
  let expired = 0;

  for (const item of input) {
    if (shouldExpireMemory(item, now)) {
      expired += 1;
      continue;
    }
    const normalized = normalizeMemoryContent(item.content);
    if (seen.has(normalized)) {
      continue;
    }
    seen.add(normalized);
    retained.push(item);
  }

  const minScore = options.minScore ?? 0.4;
  const promoted = retained
    .map((item) => ({
      item,
      score: item.confidence * 0.7 + memoryRecencyScore(item, now) * 0.3,
    }))
    .filter((entry) => entry.score >= minScore)
    .sort((left, right) => right.score - left.score)
    .slice(0, options.maxPromoted ?? 40)
    .map((entry) => entry.item);

  await store.replaceNamespace(namespace, retained);
  const vaultRoot = path.join(stateRoot, "memory");
  await ensureDir(vaultRoot);
  const vaultPath = path.join(vaultRoot, "MEMORY.md");
  await writeJson(path.join(vaultRoot, ".dreams", "latest.json"), {
    generatedAt: now.toISOString(),
    namespace,
    promotedIds: promoted.map((item) => item.id),
    retainedIds: retained.map((item) => item.id),
  });
  await writeText(vaultPath, renderMemoryVault(namespace, promoted));

  return {
    expired,
    generatedAt: now.toISOString(),
    inputItems: input.length,
    namespace,
    promoted: promoted.length,
    retained: retained.length,
    vaultPath,
  };
}

export function rerankHits(
  query: string,
  hits: RetrievalHit[],
): RetrievalHit[] {
  return [...hits].sort((left, right) => {
    const leftScore = left.score + lexicalScore(query, left.excerpt);
    const rightScore = right.score + lexicalScore(query, right.excerpt);
    return rightScore - leftScore;
  });
}
